### ISSUE TITLE
nvimcom wasn't loaded yet

### ISSUE THREAD

**Issue by isthisthat** [jalvesaq/nvimcom#2]
Hello,
I was wondering if you could help me debug why `nvimcom` is not starting in my neovim installation.
When I start R as `RVanillaStart`, I get:

    Waiting nvimcom loading...
    The package nvimcom wasn't loaded yet.

Thank you.

**Comment by jalvesaq** [comment]
This is a bug: Neovim should not wait for nvimcom in this case.

When we start R as `R --vanilla` it does not read the `~/.Rprofile` and, consequently, the nvimcom package is not loaded. I may remove the command `<LocalLeader>rv` since the user can set the value of `R_args` to `['--vanilla']`. But removing it or not, I will make the Nvim-R do not wait for nvimcom if R was started with the `--vanilla` argument.

**Comment by jalvesaq** [comment]
I fixed the bug by removing the option to start `R --vanilla`. If you need to start R vanilla, please, put in your nvimrc: `R_args = ['--vanilla']`
If the expression `"vanilla"` is part of the arguments passed to R, Neovim will not wait for nvimcom being started.

**Comment by isthisthat** [comment]
thank you for your help!
